### ISSUE TITLE
翻译的太敷衍了吧

### ISSUE THREAD

**Issue by Jianwei-Wang** [waylau/essential-netty-in-action#17]
感觉就是直接机器翻译的吧，还没有读原文理解的快。以后还会更新吗

**Comment by waylau** [comment]
@Jianwei-Wang   一直在更新呢~ 亲。

哪里不顺畅的，提出来， 我会及时改进。

**Comment by waylau** [comment]
https://github.com/waylau/essential-netty-in-action/graphs/contributors
翻译工作不易，需要大家一起努力。
如果你也参与进来，可以让进度更快一点。

**Comment by Jianwei-Wang** [comment]
感谢你们的无私贡献，翻译工作确实挺不容易的，向你们致敬。我刚接触netty，工作也比较忙，最近没时间参与。这里有另一位译者的翻译 http://ifeve.com/netty-in-action/，读着没那么拗口

**Comment by waylau** [comment]
@Jianwei-Wang   好的。感谢您的建议，校稿工作也是在逐步进行的。参与的话可以有许多方式的。比如，你指出那句话翻译的不好 反馈给我们，这也是一种简单的参与。

**Comment by lonhay** [comment]
确实翻译的比较生硬，不过还是感谢你们的贡献！
