### ISSUE TITLE
存在笔误【案例研究:Transport 的迁移】

### ISSUE THREAD

**Issue by wukonggg** [waylau/essential-netty-in-action#20]
# essential-netty-in-action/CORE FUNCTIONS/Case study transport migration.md

NettyNioServer的说明第二条写错了：

`
2.使用 OioEventLoopGroup 允许阻塞模式（Old-IO）
`

应该是

`
2.使用 NioEventLoopGroup 允许非阻塞模式（NIO）
`

**Comment by waylau** [comment]
@wukonggg   感谢，已经修正~
