### ISSUE TITLE
Netty In Action的中文正版书籍很快就要上市了

### ISSUE THREAD

**Issue by He-Pin** [waylau/essential-netty-in-action#22]
您好:很感谢您对Netty推广的付出:

目前Netty的正版书籍马上就要上市了,其中中文对应的源代码已经更新,详见下面的地址.
https://github.com/ReactivePlatform/netty-in-action-cn

因为按照版权法,没有得到版权的话其实是无法自己随便翻译的,所以请至少在您的REPO中鲜明地说明相应地信息,并且链接到对应的Repo. 以及人民邮电出版社,[异步社区](http://www.epubit.com.cn/)对应的本书页面,谢谢.

http://www.epubit.com.cn/

再次感谢您对Netty社区的贡献.

**Comment by hepin1989** [comment]
Netty In Action 中文版《Netty实战》的代码清单 ReactivePlatform/netty-in-action-cn

内容提要

本书是为想要或者正在使用 Java 从事高性能网络编程的人而写的，循序渐进地介绍了 Netty 各个方面的内容。本书共分为 4 个部分：第一部分详细地介绍 Netty 的相关概念以及核心组件，第二部分介绍 自定义协议经常用到的编解码器，第三部分介绍 Netty 对于应用层高级协议的支持，会覆盖常见 的协议及其在实践中的应用，第四部分是几个案例研究。此外，附录部分还会简单地介绍 Maven， 以及如何通过使用 Maven 编译和运行本书中的示例。阅读本书不需要读者精通 Java 网络和并发编程。如果想要更加深入地理解本书背后的理念 以及 Netty 源码本身，可以系统地学习一下 Java 网络编程、 NIO、并发和异步编程以及相关的 设计模式。

说明

这个仓库包含了Netty In Action 这本书的中文版 Netty实战 的代码清单. 为了更好地服务于读者,进行了如下方面的改进.相对于英文版本(2.0-SNAPSHOT分支):

更新了行文中的注释
按照中文版本的排版进行了调整
所有的代码清单以及跳转都使用了中文版书籍中的翻译

**Comment by waylau** [comment]
@hepin1989  感谢您的反馈！
同时感谢您对Netty社区的贡献。
期待您的作品能给广大Netty 爱好者带来福音！

在您作品上市后，我这边会做出一定的调整~

**Comment by He-Pin** [comment]
@waylau 我也补充了 V2ex 上的一些说明，您可以看下哦，很遗憾当初没有邀请到您来一起合作。
https://www.v2ex.com/t/356574#reply38
