### ISSUE TITLE
《Netty 实战》中文版已经上市了

### ISSUE THREAD

**Issue by He-Pin** [waylau/essential-netty-in-action#23]
@waylau ，如之前的 issue，目前中文版已经上架京东了哈：

https://item.jd.com/12070975.html
http://www.epubit.com.cn/book/details/4228

谢谢了哦。

**Comment by TakWolf** [comment]
关注很久，已下单，希望可以早点发货

**Comment by He-Pin** [comment]
[《Netty实战》Netty In Action中文版——文前内容](http://ifeve.com/netty-in-action-intro/)
[《Netty 实战》Netty In Action中文版 第2章——你的第一款Netty应用程序](http://ifeve.com/netty-in-action-2/)
[《Netty实战》Netty In Action中文版 第1章——Netty——异步和事件驱动](http://ifeve.com/netty-in-action-1/)

**Comment by waylau** [comment]
@hepin1989  首页说明，把该书的信息给放上去了，期待您的作品大卖！

**Comment by He-Pin** [comment]
哈哈哈，找了半天终于找到了，谢谢哈。
