### ISSUE TITLE
2.4.3节Encoder(编码器)勘误类名ChanneOutboundHandler错误

### ISSUE THREAD

**Issue by zunchen** [waylau/essential-netty-in-action#26]
2.4.3节Encoder(编码器)类名错误：
本章节第一句话原文：

> 回顾之前的定义，encoder是用来把出站数据从一种格式转换到另外一种格式，因此它实现了ChanneOutboundHandler 。

 这里的ChanneOutboundHandler类名错误，应为ChannelOutboundHandler

**Comment by waylau** [comment]
@zunchen  感谢您的反馈。问题已经修复。
