### ISSUE TITLE
ByteBuf章节的小错误

### ISSUE THREAD

**Issue by guang19** [waylau/essential-netty-in-action#32]
这是我发现的与 《netty实战》 的一个不同之处：

你写的是CompositeByteBuf.hasArray总是返回false，

![image](https://user-images.githubusercontent.com/41150022/85921389-a2995700-b8ae-11ea-90f8-fca605579a77.png)

而《Netty实战》 上写的是 如果CompositeByteBuf 只有一个ByteBuf ， 那么CompositeByteBuf的hasArray返回该ByteBuf的hasArray的结果，否则返回false，

![image](https://user-images.githubusercontent.com/41150022/85921516-73371a00-b8af-11ea-92cf-e90f55cbabe9.png)

在我查阅相关源码之后，发现源码应该是符合 《Netty实战》 的描述，所以可能是你的描述错误。

![image](https://user-images.githubusercontent.com/41150022/85921602-e2ad0980-b8af-11ea-9c5c-99c9ef40a117.png)

**Comment by waylau** [comment]
@guang19  已经修正，感谢反馈！
see  https://github.com/waylau/essential-netty-in-action/pull/33
